CREATE TABLE `point`.`user` (
	`id` BIGINT(20) NOT NULL,	
	`email` VARCHAR(50) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`role` VARCHAR(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `point`.`user` ADD PRIMARY KEY (`id`);

ALTER TABLE `point`.`user` MODIFY `id` BIGINT(20) NOT NULL AUTO_INCREMENT;